### ISSUE TITLE
Can't handle source exceptions - 'Exception ignored from cffi callback'

### ISSUE THREAD

**Issue by alexitx** [irmen/pyminiaudio#40] opened 2021-11-02 15:04 UTC
The iterator of stream_any can't handle exceptions that occur in the StreamableSource. Instead the library continues to try to read data and spams traceback to stdout (sometimes an error message window from CFFI opens). I don't see any way to prevent this currently except swallowing all exceptions that might come from the read method, including KeyboardInterrupt.

I think it will be more suitable to raise those exceptions from the generator itself since it already blocks while reading, or re-raise DecoderError with the original exception's args and message and only pass through KeyboardInterrupt.

Example code:
```python
import miniaudio
import requests

class StreamableSource(miniaudio.StreamableSource):

    def __init__(self):
        # HTTP stream or file-like object
        self.fh = requests.get('http://us4.internet-radio.com:8258/stream', timeout=5.0, stream=True).raw
        self.i = 0

    def read(self, size):
        print(f'Reading {size}')
        self.i += 1
        # Raise exception after the 5th read
        if self.i >= 5:
            raise ValueError('Some exception')
        return self.fh.read(size)

source = StreamableSource()
generator = miniaudio.stream_any(source, frames_to_read=16384)
try:
    for frames in generator:
        print(len(frames))
except Exception as e:
    # Never raises to get caught
    print(f'Caught {type(e).__name__}: {e}')
```

Output:
```
...
Exception ignored from cffi callback <function _internal_decoder_read_callback at 0x00000159E439BDC0>:
Traceback (most recent call last):
  File "venv\lib\site-packages\miniaudio.py", line 1241, in _internal_decoder_read_callback
    data = source.read(num_bytes)
  File "miniaudio_test.py", line 15, in read
    raise ValueError('Some exception')
ValueError: Some exception
...
```

**Comment by irmen** [comment] 2021-11-27 18:47
I'll look into this.

**Comment by irmen** [comment] 2021-11-28 22:33
I pushed a change to the master branch that should improve this. With it, your example code correctly catches the decode error. Can you have a look?
18849c9a07d905c50225a415912403d3681cba14

**Comment by alexitx** [comment] 2021-11-29 02:43
Seems to be working as expected now.

Only KeyboardInterrupt still results in callback exception when reading from the generator directly instead of using a Device class. Though I'm not sure how and if this should be handled by pyminiaudio. Perhaps closing the stream and re-raising the exception or wrapping it with try-finally statement like other libraries (subprocess, sounddevice) do?

I also couldn't find any information on catching or silencing CFFI exceptions externally, probably because it's a bad practice to silently ignore them. But CFFI error messages on Windows can be an issue if we're relying on exceptions for flow control.

Though I'm personally happy with the current changes.

**Comment by irmen** [comment] 2021-11-29 17:35
I'm not sure if the handling of KeyboardInterrupt is deterministic in Python when dealing with multiple threads.  Remember that the generator callback is running in a background thread (initiated by the miniaudio backend).

**Comment by alexitx** [comment] 2021-11-29 17:49
So there shouldn't be any resource leaks if KeyboardInterrupt is unhandled? I'm not very familiar with C, so I don't know how miniaudio handles such cases either.

**Comment by irmen** [comment] 2021-11-29 18:02
I guess I can try to catch KeyboardInterupt as well and try to re-raise it from the generator.

**Comment by alexitx** [comment] 2021-12-01 15:25
Sorry for the delay, I was able to test the latest changes just now.

Your concerns about the background thread were correct. KeyboardInterrupt doesn't always get re-raised properly. Sometimes DecodeError gets raised instead, other times it gets swallowed completely and I was able to deadlock the generator by hitting ^C in just the right moment. I think not handling KeyboardInterrupt is better in this case.

**Comment by irmen** [comment] 2021-12-01 15:46
Oh, that's unfortunate. The few tests I did seemed to work ok with handling the ^C. But yeah, other behavior could be caused by pressing ^C in the middle of a filesystem or socket I/O operation.   Handling it is dangerous territory.  Python KeyboardInterrupt is not a subclass of Exception on purpose.

I'll revert the last change and then close this issue as I think the other change is good!

**Closed** 2021-12-01 20:51 UTC
Labels: enhancement
